### ISSUE TITLE
1. Initialize-Application

### ISSUE THREAD

**Issue by Sayed94h** [Sayed94h/Portfolio-GitHub-API#3]
## 1. Initialize Application

**As a user I want to see the initial page when I load the site**

- \_Given [context] when [a specific action is performed] then [a set of consequences should occur]\_\_
- ...

### REPO

- [x] This user story is developed on branch `initial-app`.
-  [x] This branch is merged to `master` branch after completion.

### Task A: HTML

- [x] Finished the HTML part of the web page

### Task B: CSS

- [x] Finished most part of the style for the web page

### Task C: JavaScript

- [x] Added some function for writing text one screen
- [x] Added a function to display or hide some contents in footer

---
