### ISSUE TITLE
Render Repos

### ISSUE THREAD

**Issue by Sayed94h** [Sayed94h/Portfolio-GitHub-API#5]
## 2. Render All Repositories

**As a user I want to see all of the repositories**

- \_Given [context] when [a specific action is performed] then [a set of consequences should occur]\_\_
- ...

### REPO

- [x] This user story is developed on branch `render-repos`.
- [x] This branch is merged to `master` branch after completion.

### Task A: HTML

- [x] Added `a tags` with JS

### Task B: CSS

- [x] Added style for this part

### Task C: JavaScript

- [x] Getting repos using fetch
- [x] Converting the data to JSON file
- [x] Render the repos's name and url in `a tags`

---
